version: '3.2'

services:

  irowor_local:
    container_name: irowor
    image: piousbox/php83:0.0.0
    ports:
      - 9101:80
    restart: 'unless-stopped'
    volumes:
      - irowor_data:/var/www/html
      - type: bind
        source: config/settings.php
        target: /var/www/html/sites/default/settings.php
      - type: bind
        source: config/development.services.yml
        target: /var/www/html/sites/development.services.yml
      - type: bind
        source: .
        target: /var/www/html/modules/custom/irowor_drupal_module
      - ./empty:/var/www/html/modules/custom/irowor_drupal_module/tmp

volumes:
  irowor_data:
